- name: Copy Redis repo file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install Redis Server
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Restart Redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
