- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Remove old html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download frontend content & extract
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes
