- name: Set Up server configuration
  ansible.builtin.import_tasks: server.yml
  when: PROMETHEUS_INSTALL_TYPE == "server"

- name: Set Up client configuration
  ansible.builtin.import_tasks: client.yml
  when: PROMETHEUS_INSTALL_TYPE == "client"