- name: setup hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Install Galaxy General collection
  ansible.builtin.shell: ansible-galaxy collection install community.general
  when: APP_TYPE == "nodejs"
  become_user: roboshop