- name: setup hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Install prometheus node exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: client

- name: Create rsyslog configuration
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/{{COMPONENT}}.conf
  when: APP_TYPE == "java" or APP_TYPE == "python" or APP_TYPE == "nodejs" or APP_TYPE == "golang"

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  when: APP_TYPE == "java" or APP_TYPE == "python" or APP_TYPE == "nodejs" or APP_TYPE == "golang"

- name: Install Ansible SSM Python3 Deps
  ansible.builtin.pip:
    name: "{{item}}"
    executable: pip3
  loop:
    - botocore
    - boto3