global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
  - alert-rules.yml

#scrape_configs:
# - job_name: "prometheus"
#   static_configs:
#     - targets: ["172.31.86.2:9100"]

scrape_configs:
  - job_name: ec2-nodes
    ec2_sd_configs:
      - region: "us-east-1"
        port: 9100
        filters:
          - name: "tag:Monitor"
            values: ["Yes"]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: "component"