global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

#scrape_configs:
# - job_name: "prometheus"
#   static_configs:
#     - targets: ["172.31.86.2:9100"]

scrape_configs:
  - job_name: ec2-nodes
    ec2_sd_configs:
      - region: "us-east-1"
        port: 9100
